# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

## Adds CICD Trigger via Pull Request
pr:
  branches:
    include:
    - master
  paths:
    include:
    - PowerBI/*

pool:
  vmImage: 'vs2017-win2016'

## BUILD ###
stages:
- stage: BUILD
  jobs:
  - job: "Build"
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/PowerBI/'
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)/PowerBI'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/PowerBI'
        ArtifactName: 'PowerBI'
        publishLocation: 'Container'

### RELEASE - DEV ###
- stage: DEV
  variables:
    - group: PowerBI-Dev  # Variable Group used for PowerBI Deployments
  jobs:
    - deployment: DeployWeb
      displayName: deploy Web App
      pool:
        vmImage: 'vs2017-win2016'
      environment: 'DEV'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadPipelineArtifact@2
              displayName: 'Download artefacts'
              inputs:
                artifact: 'PowerBI'
                path: $(Build.SourcesDirectory)\bin

      # Remarks: Deployment of Shared Dataset in DEV is disabled
      #- task: PowerShell@2
      #  displayName: 'Deploy Shared Dataset'
      #  inputs:
      #      filePath: '$(System.DefaultWorkingDirectory)\bin\Scripts\Deploy-SharedDataSet.ps1'
      #      arguments: '-PowerBIFilePath "$(System.DefaultWorkingDirectory)\bin\$(SharedDataset.Folder)\$(SharedDataset.Name).pbix" -WorkspaceName "$(SharedDataSet.Workspace.Name)" -SharedDatasetName "$(SharedDataset.Name)" -BuildAgentLogin "$(BuildAgent.Name)" -BuildAgentPassword "$(BuildAgent.Password)" -SourceSqlServer "$(SqlServer.Name)" -SourceDatabase "$(SqlServer.Database.Name)" -GatewayName "$(Gateway.Name)" -InstallLibraries "True"'

            - task: PowerShell@2
              displayName: 'Deploy Reports'
              inputs:
                filePath: '$(System.DefaultWorkingDirectory)\bin\Scripts\Deploy-PowerBIReports.ps1'
                arguments: '-PowerBIDirectory "$(System.DefaultWorkingDirectory)\bin\Report" -DatasetWorkspaceName "$(SharedDataSet.Workspace.Name)" -DatasetName "$(SharedDataset.Name)" -BuildAgentLogin "$(BuildAgent.Name)" -BuildAgentPassword "$(BuildAgent.Password)" -ReportsToDeploy ''$(Reports.ConfigurationJson)'''

