## Adds CICD Trigger via Pull Request
pr:
  branches:
    include:
    - master
  paths:
    include:
    - PowerBI/*

pool:
  vmImage: 'vs2017-win2016'

## BUILD ###
stages:
- stage: BUILD
  jobs:
  - job: "Build"
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/PowerBI/'
        Contents: '**'
        TargetFolder: '$(build.artifactstagingdirectory)/PowerBI'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/PowerBI'
        ArtifactName: 'PowerBI'
        publishLocation: 'Container
stages:
- stage: Deploy
  jobs:
   job: "Deploy"
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: 'PowerBI'
        path: $(Build.SourcesDirectory)\bin"$(SharedDataSet.Workspace.Name)" -SharedDatasetName "$(SharedDataset.Name)" -BuildAgentLogin "$(BuildAgent.Name)" -BuildAgentPassword "$(BuildAgent.Password)" -SourceSqlServer "$(SqlServer.Name)" -SourceDatabase "$(SqlServer.Database.Name)" -GatewayName "$(Gateway.Name)" -InstallLibraries "True"'
    - task: PowerShell@2
      inputs:
        displayName: 'Deploy Reports'  
        filePath: '$(System.DefaultWorkingDirectory)\bin\Scripts\Deploy-PowerBIReports.ps1'
        arguments: '-PowerBIDirectory "$(System.DefaultWorkingDirectory)\bin\Report" -DatasetWorkspaceName "$(SharedDataSet.Workspace.Name)" -DatasetName "$(SharedDataset.Name)" -BuildAgentLogin "$(BuildAgent.Name)" -BuildAgentPassword "$(BuildAgent.Password)" -ReportsToDeploy ''$(Reports.ConfigurationJson)'''



